apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.name }}
  namespace: default
spec:
  selector:
    app: {{ .Chart.name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.service.port }}
  type: ClusterIP
