apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbo-express
  namespace: default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0  # This ensures at least one pod stays running
      maxSurge: 4        # Allow extra pods during the rollout
  selector:
    matchLabels:
      app: turbo-express
  template:
    metadata:
      labels:
        app: turbo-express
    spec:
      containers:
      - name: turbo-express
        image: harbor.marcmarina.com/library/turbo-playground
        command: ["node", "apps/express-app"]
        ports:
        - containerPort: 8081  # Update with your app's port
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_FORMAT
          value: "json"
        - name: ENABLE_REQUEST_LOGGING
          value: "true"
        - name: PORT
          value: "8081"
        - name: API_HOST
          value: "http://turbo.default"
        resources:          # Add this section
          limits:
            cpu: "500m"
            memory: "250Gi"
          requests:
            cpu: "250m"
            memory: "512Mi"
      # Only needed if Harbor requires auth:
      imagePullSecrets:
      - name: harbor-creds
