apiVersion: v1
kind: Service
metadata:
  name: turbo-express
  namespace: default
spec:
  selector:
    app: turbo-express
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081  # Must match containerPort above
  type: ClusterIP
