namespace: default

image:
  repository: harbor.marcmarina.com/library/turbo-playground
  tag: latest
  pullPolicy: IfNotPresent

container:
  command: ["node", "apps/express-app"]
  port: 8080

deployment:
  replicaCount: 2
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  preStop:
    delay: 5

metrics:
  endpoint: /metrics

resources:
  requests:
    cpu: 250m
    memory: 250Mi
  limits:
    cpu: 500m
    memory: 512Mi

readinessProbe:
  path: /_health

livenessProbe:
  path: /_health

service:
  type: ClusterIP
  port: 80

ingress:
  host: turbo-express.marc-lab.dev

env:
 LOG_LEVEL: info
 LOG_FORMAT: json
 ENABLE_REQUEST_LOGGING: false
 PORT: 8080
 API_HOST: http://turbo
