namespace: default

image:
  repository: harbor.marcmarina.com/library/turbo-playground
  tag: latest
  pullPolicy: IfNotPresent

container:
  command: "['node', 'apps/express-app']"
  port: 8080

deployment:
  replicaCount: 2
  preStop:
    delay: 5

readinessProbe:
  path: /health

livenessProbe:
  path: /health

service:
  type: ClusterIP
  port: 80

ingress:
  host: turbo-express.marc-lab.dev

env:
 LOG_LEVEL: info
 LOG_FORMAT: json
 ENABLE_REQUEST_LOGGING: true
 PORT: 8080
 API_HOST: http://turbo
