apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: turbo-react
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: turbo.frontend.marcmarina.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: turbo-react
            port:
              number: 80
