apiVersion: v1
kind: Service
metadata:
  name: turbo
  namespace: backend
spec:
  selector:
    app: turbo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081  # Must match containerPort above
  type: ClusterIP
